# Generated by Django 3.0.7 on 2021-04-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sharekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
